name: "Export Homebrew build paths for CGO"
description: "An action to export brew library paths for macOS"
inputs:
runs:
  using: "composite"
  steps:
    - run: |
        echo "C_INCLUDE_PATH=/usr/local/include:/opt/homebrew/include:$C_INCLUDE_PATH" >> $GITHUB_ENV
        echo "LIBRARY_PATH=/usr/local/lib:/opt/homebrew/lib:$LIBRARY_PATH" >> $GITHUB_ENV
        echo "CGO_CFLAGS=-I/usr/local/include -I/opt/homebrew/include" >> $GITHUB_ENV
        echo "CGO_LDFLAGS=-L/usr/local/lib -L/opt/homebrew/lib" >> $GITHUB_ENV
      shell: bash
branding:
  icon: "terminal"
  color: "yellow"
